import type { Metadata } from "next";
import { SITE_NAME, SITE_URL } from "@/lib/site";
import { OG_ALT, OG_SIZE } from "@/lib/og";

// Generated by app/opengraph-image.tsx and app/twitter-image.tsx. Set
// explicitly because a page-level openGraph object replaces the inherited one.
const OG_IMAGE = { url: "/opengraph-image", ...OG_SIZE, alt: OG_ALT };

interface PageMeta {
  /** Full title tag (rendered as-is, no template). */
  title: string;
  /** Unique per page: location keyword + offer + CTA. */
  description: string;
  /** Path beginning with "/". */
  path: string;
  noIndex?: boolean;
}

/**
 * Per-page metadata with canonical URL and Open Graph/Twitter tags.
 */
export function pageMetadata({ title, description, path, noIndex }: PageMeta): Metadata {
  const url = `${SITE_URL}${path === "/" ? "/" : path}`;
  return {
    title: { absolute: title },
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      locale: "en_US",
      siteName: SITE_NAME,
      title,
      description,
      url,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ["/twitter-image"],
    },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
  };
}
